<?php

namespace Database\Seeders;

use App\Models\Resource;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Route;

class ResourceSeeder extends Seeder
{
    public function run(): void
    {
        collect(
            [
                [
                    'name' => 'Dashboard',
                    'route_name' => 'backoffice.dashboard',
                    'icon' => 'tachometer-alt',
                    'order' => 2,
                    'description' => 'System overview dashboard',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'access-backoffice',
                    'morph_class' => null,
                ],
                [
                    'name' => 'POS',
                    'route_name' => 'backoffice.pos',
                    'icon' => 'cash-register',
                    'order' => 1,
                    'description' => 'Point of Sale section',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'access-pos',
                    'morph_class' => null,
                ],
                [
                    'name' => 'Individuals',
                    'route_name' => 'backoffice.individuals.index',
                    'icon' => 'user',
                    'order' => 3,
                    'description' => 'Manage individual persons',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-individuals',
                    'morph_class' => 'individual',
                ],
                [
                    'name' => 'Users',
                    'route_name' => 'backoffice.users.index',
                    'icon' => 'users',
                    'order' => 5,
                    'description' => 'System users management',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-users',
                    'morph_class' => 'user',
                ],
                [
                    'name' => 'Brands',
                    'route_name' => 'backoffice.brands.index',
                    'icon' => 'tags',
                    'order' => 6,
                    'description' => 'Product brands and manufacturers',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-brands',
                    'morph_class' => 'brand',
                ],
                [
                    'name' => 'Stores',
                    'route_name' => 'backoffice.stores.index',
                    'icon' => 'store',
                    'order' => 7,
                    'description' => 'Manage physical or virtual stores',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-stores',
                    'morph_class' => 'store',
                ],
                [
                    'name' => 'Item Categories',
                    'route_name' => 'backoffice.item-categories.index',
                    'icon' => 'layer-group',
                    'order' => 8,
                    'description' => 'Organize items into categories',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-item-categories',
                    'morph_class' => 'item-category',
                ],
                [
                    'name' => 'Items',
                    'route_name' => 'backoffice.items.index',
                    'icon' => 'box',
                    'order' => 9,
                    'description' => 'Manage all inventory items',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-items',
                    'morph_class' => 'item',
                ],
                [
                    'name' => 'Item Variants',
                    'route_name' => 'backoffice.item-variants.index',
                    'icon' => 'boxes',
                    'order' => 10,
                    'description' => 'Variants for individual items',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-item-variants',
                    'morph_class' => 'item-variant',
                ],
                [
                    'name' => 'Stock Levels',
                    'route_name' => 'backoffice.stock-levels.index',
                    'icon' => 'warehouse',
                    'order' => 11,
                    'description' => 'Track available inventory stock',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-stock-levels',
                    'morph_class' => 'stock-level',
                ],
                [
                    'name' => 'Stock Movements',
                    'route_name' => 'backoffice.stock-movements.index',
                    'icon' => 'exchange-alt',
                    'order' => 12,
                    'description' => 'Monitor stock in/out flow',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-stock-movements',
                    'morph_class' => 'stock-movement',
                ],
                [
                    'name' => 'Purchases',
                    'route_name' => 'backoffice.purchases.index',
                    'icon' => 'shopping-cart',
                    'order' => 13,
                    'description' => 'Handle product purchases',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-purchases',
                    'morph_class' => 'purchase',
                ],
                [
                    'name' => 'Orders',
                    'route_name' => 'backoffice.orders.index',
                    'icon' => 'receipt',
                    'order' => 14,
                    'description' => 'Customer order management',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-orders',
                    'morph_class' => 'order',
                ],
                [
                    'name' => 'Permissions',
                    'route_name' => 'backoffice.permissions.index',
                    'icon' => 'unlock-alt',
                    'order' => 15,
                    'description' => 'Assign and manage permissions',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-permissions',
                    'morph_class' => 'permission',
                ],
                [
                    'name' => 'Roles',
                    'route_name' => 'backoffice.roles.index',
                    'icon' => 'user-shield',
                    'order' => 16,
                    'description' => 'User role and access control',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-roles',
                    'morph_class' => 'role',
                ],
                [
                    'name' => 'Organiztion Categories',
                    'route_name' => 'backoffice.organization-categories.index',
                    'icon' => 'sitemap',
                    'order' => 18,
                    'description' => 'Organize individuals and companies',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-organization-categories',
                    'morph_class' => 'organization-category',
                ],
                [
                    'name' => 'Organizations',
                    'route_name' => 'backoffice.organizations.index',
                    'icon' => 'building',
                    'order' => 19,
                    'description' => 'Manage organizations',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-organizations',
                    'morph_class' => 'organization',
                ],
                [
                    'name' => 'Resources',
                    'route_name' => 'backoffice.resources.index',
                    'icon' => 'toolbox',
                    'order' => 17,
                    'description' => 'Resources and pages that can be accessed by users',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-resources',
                    'morph_class' => 'role',
                ],
                [
                    'name' => 'Carousels',
                    'route_name' => 'backoffice.carousels.index',
                    'icon' => 'right-left',
                    'order' => 20,
                    'description' => 'The shopping section carousels +',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-carousels',
                    'morph_class' => 'carousel',
                ],
                [
                    'name' => 'Services',
                    'route_name' => 'backoffice.services.index',
                    'icon' => 'tag',
                    'order' => 21,
                    'description' => 'The list of service we provide',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-services',
                    'morph_class' => 'service',
                ],
                [
                    'name' => 'Settings',
                    'route_name' => 'backoffice.settings.show',
                    'icon' => 'cog',
                    'order' => 21,
                    'description' => 'Sytem wide settings',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'manage-settings',
                    'morph_class' => null,
                ],
                [
                    'name' => 'Payments',
                    'route_name' => 'backoffice.payments.index',
                    'icon' => 'credit-card',
                    'order' => 22,
                    'description' => 'Payment methods and transactions',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-payments',
                    'morph_class' => 'payment',
                ],
                [
                    'name' => 'Transactions',
                    'route_name' => 'backoffice.transactions.index',
                    'icon' => 'money-bill-wave',
                    'order' => 23,
                    'description' => 'Financial transactions and history',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-transactions',
                    'morph_class' => 'transaction',
                ],
                [
                    'name' => 'Payment Methods',
                    'route_name' => 'backoffice.payment-methods.index',
                    'icon' => 'credit-card',
                    'order' => 24,
                    'description' => 'Manage payment methods',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-payment-methods',
                    'morph_class' => 'payment-method',
                ],
                [
                    'name' => 'Quotations',
                    'route_name' => 'backoffice.quotations.index',
                    'icon' => 'file-invoice',
                    'order' => 25,
                    'description' => 'Manage customer quotations',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-quotations',
                    'morph_class' => 'quotation',
                ],
                [
                    'name' => 'Notifications',
                    'route_name' => 'backoffice.notifications.index',
                    'icon' => 'bell',
                    'order' => 26,
                    'description' => 'System notifications and alerts',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-notifications',
                ],
                [
                    'name' => 'Agreements',
                    'route_name' => 'backoffice.agreements.index',
                    'icon' => 'file-contract',
                    'order' => 27,
                    'description' => 'Manage customer agreements',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-agreements',
                    'morph_class' => 'agreement',
                ],
                [
                    'name' => 'Contacts',
                    'route_name' => 'backoffice.contacts.index',
                    'icon' => 'address-book',
                    'order' => 28,
                    'description' => 'Manage contacts and communication',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-contacts',
                    'morph_class' => 'contact',
                ],
                [
                    'name' => 'Reports',
                    'route_name' => 'backoffice.reports.index',
                    'icon' => 'chart-bar',
                    'order' => 29,
                    'description' => 'Generate and view reports',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-reports',
                    'morph_class' => null,
                ],
                [
                    'name' => 'Activities',
                    'route_name' => 'backoffice.activities.index',
                    'icon' => 'history',
                    'order' => 30,
                    'description' => 'View system activity logs',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-activities',
                    'morph_class' => 'activity',
                ],
                [
                    'name' => 'Messages',
                    'route_name' => 'backoffice.messages.index',
                    'icon' => 'envelope',
                    'order' => 31,
                    'description' => 'Manage system messages',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-messages',
                    'morph_class' => 'message',
                ],
                [
                    'name' => 'Employees',
                    'route_name' => 'backoffice.employees.index',
                    'icon' => 'users-cog',
                    'order' => 32,
                    'description' => 'Manage employee records',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-employees',
                    'morph_class' => 'employee',
                ],
                [
                    'name' => 'Employment',
                    'route_name' => 'backoffice.employment.show',
                    'icon' => 'briefcase',
                    'order' => 33,
                    'description' => 'Manage employment records',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'read-employment',
                    'morph_class' => 'employment',
                ],
                [
                    'name' => 'Contracts',
                    'route_name' => 'backoffice.contracts.index',
                    'icon' => 'file-contract',
                    'order' => 34,
                    'description' => 'Manage employees contracts',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-contracts',
                    'morph_class' => 'contract',
                ],
                [
                    'name' => 'Suspensions',
                    'route_name' => 'backoffice.suspensions.index',
                    'icon' => 'ban',
                    'order' => 35,
                    'description' => 'Manage employees suspensions',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-suspensions',
                    'morph_class' => 'suspension',
                ],
                [
                    'name' => 'Media',
                    'route_name' => 'backoffice.media.index',
                    'icon' => 'image',
                    'order' => 36,
                    'description' => 'System media plus',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-media',
                    'morph_class' => 'media',
                ],
                [
                    'name' => 'Accounting',
                    'route_name' => 'backoffice.accounting.index',
                    'icon' => 'money-bill',
                    'order' => 37,
                    'description' => 'Manage accounting records',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-accounting-periods',
                    'morph_class' => null,
                ],
                [
                    'name' => 'Taxes',
                    'route_name' => 'backoffice.taxes.index',
                    'icon' => 'file-invoice-dollar',
                    'order' => 38,
                    'description' => 'Manage tax records',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-taxes',
                    'morph_class' => 'tax',
                ],
                [
                    'name' => 'Properties',
                    'route_name' => 'backoffice.properties.index',
                    'icon' => 'building',
                    'order' => 39,
                    'description' => 'Manage property records',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-properties',
                    'morph_class' => 'property',
                ],
                [
                    'name' => 'Buildings',
                    'route_name' => 'backoffice.buildings.index',
                    'icon' => 'building',
                    'order' => 40,
                    'description' => 'Manage building records',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-buildings',
                    'morph_class' => 'building',
                ],
                [
                    'name' => 'Rooms',
                    'route_name' => 'backoffice.rooms.index',
                    'icon' => 'door-open',
                    'order' => 41,
                    'description' => 'Manage room records',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-rooms',
                    'morph_class' => 'room',
                ],
                [
                    'name' => 'Bookings',
                    'route_name' => 'backoffice.bookings.show',
                    'icon' => 'calendar-check',
                    'order' => 42,
                    'description' => 'Manage bookings records',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-bookings',
                    'morph_class' => null,
                ],
                [
                    'name' => 'Reservations',
                    'route_name' => 'backoffice.reservations.index',
                    'icon' => 'calendar-alt',
                    'order' => 43,
                    'description' => 'Manage reservations records',
                    'is_active' => true,
                    'count' => 0,
                    'required_permission' => 'browse-reservations',
                    'morph_class' => null,
                ],
            ]
        )->each(function ($item, $index) {

            if (! Route::has($item['route_name'])) {
                return;
            }

            $attributes = [
                'route_name' => data_get($item, 'route_name'),
            ];

            $values = [
                'name' => data_get($item, 'name'),
                'icon' => data_get($item, 'icon'),
                'description' => data_get($item, 'description'),
                'is_active' => data_get($item, 'is_active'),
                'count' => data_get($item, 'count'),
                'required_permission' => data_get($item, 'required_permission'),
                'morph_class' => data_get($item, 'morph_class'),
                'order' => $index + 1,
            ];

            Resource::query()->firstOrCreate($attributes, $values);
        });
    }
}
