<?php

use App\Http\Controllers\Backoffice\DashboardController;
use App\Http\Controllers\Backoffice\POSController;
use App\Http\Controllers\Backoffice\POSStoreController;
use Illuminate\Support\Facades\Route;

Route::get('/', DashboardController::class)->name('dashboard');
Route::get('/pos', [POSController::class, 'show'])->middleware(['can:access-pos'])->name('pos');
Route::post('/pos', [POSController::class, 'process'])->middleware(['can:access-pos'])->name('pos');
Route::post('/pos/store/update', [POSStoreController::class, 'update'])->middleware(['can:access-pos'])->name('pos.store.update');

Route::prefix('users')->as('users.')->group(base_path('routes/backoffice/users.php'));
Route::prefix('item-categories')->as('item-categories.')->group(base_path('routes/backoffice/item-categories.php'));
Route::prefix('brands')->as('brands.')->group(base_path('routes/backoffice/brands.php'));
Route::prefix('services')->as('services.')->group(base_path('routes/backoffice/services.php'));
Route::prefix('properties')->as('properties.')->group(base_path('routes/backoffice/properties.php'));
Route::prefix('stores')->as('stores.')->group(base_path('routes/backoffice/stores.php'));
Route::prefix('items')->as('items.')->group(base_path('routes/backoffice/items.php'));
Route::prefix('item-variants')->as('item-variants.')->group(base_path('routes/backoffice/item-variants.php'));
Route::prefix('individuals')->as('individuals.')->group(base_path('routes/backoffice/individuals.php'));
Route::prefix('stock-levels')->as('stock-levels.')->group(base_path('routes/backoffice/stock-levels.php'));
Route::prefix('stock-movements')->as('stock-movements.')->group(base_path('routes/backoffice/stock-movements.php'));
Route::prefix('purchases')->as('purchases.')->group(base_path('routes/backoffice/purchases.php'));
Route::prefix('orders')->as('orders.')->group(base_path('routes/backoffice/orders.php'));
Route::prefix('quotations')->as('quotations.')->group(base_path('routes/backoffice/quotations.php'));
Route::prefix('permissions')->as('permissions.')->group(base_path('routes/backoffice/permissions.php'));
Route::prefix('roles')->as('roles.')->group(base_path('routes/backoffice/roles.php'));
Route::prefix('resources')->as('resources.')->group(base_path('routes/backoffice/resources.php'));
Route::prefix('organization-categories')->as('organization-categories.')->group(base_path('routes/backoffice/organization-categories.php'));
Route::prefix('organizations')->as('organizations.')->group(base_path('routes/backoffice/organizations.php'));
Route::prefix('carousels')->as('carousels.')->group(base_path('routes/backoffice/carousels.php'));
Route::prefix('settings')->as('settings.')->group(base_path('routes/backoffice/settings.php'));
Route::prefix('payments')->as('payments.')->group(base_path('routes/backoffice/payments.php'));
Route::prefix('transactions')->as('transactions.')->group(base_path('routes/backoffice/transactions.php'));
Route::prefix('payment-methods')->as('payment-methods.')->group(base_path('routes/backoffice/payment-methods.php'));
Route::prefix('notifications')->as('notifications.')->group(base_path('routes/backoffice/notifications.php'));
Route::prefix('agreements')->as('agreements.')->group(base_path('routes/backoffice/agreements.php'));
Route::prefix('contacts')->as('contacts.')->group(base_path('routes/backoffice/contacts.php'));
Route::prefix('reports')->as('reports.')->group(base_path('routes/backoffice/reports.php'));
Route::prefix('activities')->as('activities.')->group(base_path('routes/backoffice/activities.php'));
Route::prefix('messages')->as('messages.')->group(base_path('routes/backoffice/messages.php'));
Route::prefix('employees')->as('employees.')->group(base_path('routes/backoffice/employees.php'));
Route::prefix('employment')->as('employment.')->group(base_path('routes/backoffice/employment.php'));
Route::prefix('contracts')->as('contracts.')->group(base_path('routes/backoffice/contracts.php'));
Route::prefix('suspensions')->as('suspensions.')->group(base_path('routes/backoffice/suspensions.php'));
Route::prefix('media')->as('media.')->group(base_path('routes/backoffice/media.php'));
Route::prefix('accounting')->as('accounting.')->group(base_path('routes/backoffice/accounting.php'));
Route::prefix('taxes')->as('taxes.')->group(base_path('routes/backoffice/taxes.php'));
Route::prefix('buildings')->as('buildings.')->group(base_path('routes/backoffice/buildings.php'));
Route::prefix('rooms')->as('rooms.')->group(base_path('routes/backoffice/rooms.php'));
Route::prefix('bookings')->as('bookings.')->group(base_path('routes/backoffice/bookings.php'));
